language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs 
install:
  - echo "nothing needs to be installed"

# scripts to be run such as tests
before_script:
  - echo "no tests" 

script:
  - docker --version # print the docker version for logging
  
  - docker-compose -f docker-compose-build.yaml build --parallel

  - docker tag udagram-api-feed roberto77/udagram-api-feed:v4

  - docker tag udagram-api-user roberto77/udagram-api-user:v4

  - docker tag udagram-frontend roberto77/udagram-frontend:v3

  - docker tag reverseproxy roberto77/reverseproxy:v3


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push roberto77/reverseproxy:v3
  - docker push roberto77/udagram-api-user:v4
  - docker push roberto77/udagram-api-feed:v4
  - docker push roberto77/udagram-frontend:v3


  