apiVersion: v1
kind: Secret

metadata: 
  name: aws-secret-credentials
type: Opaque
data:
  aws_access_key_id: QUtJQVMzRVFESUxCUEc3RUQ1NTQ=
  aws_secret_access_key: QjZ1QkRXem1YYjVoWGVhYnNZQWJ5UUR5a0tGejFpSmc2WTA1N2xhSA==
